use CourseHub;

INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (1,'Tohoku University','Bismarck','North Dakota',58505);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (2,'University of Bunkyo','Cincinnati','Ohio',45243);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (3,'Kuwait International Law School','Philadelphia','Pennsylvania',19104);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (4,'Mahatma Gandhi University Meghalaya','Orlando','Florida',32830);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (5,'European School of Economics','Monticello','Minnesota',55590);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (6,'Zhejiang University','Fairfax','Virginia',22036);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (7,'Instituto Universitario de Ciencias de la Salud Fundación H.A. Barceló','Saint Louis','Missouri',63121);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (8,'Hastings College','Chico','California',95973);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (9,'Islamia University of Bahawalpur','Baltimore','Maryland',21281);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (10,'Instituto Superior de Ciências do Trabalho e da Empresa','Madison','Wisconsin',53705);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (11,'Gauhati University','New York City','New York',10270);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (12,'Wentworth Institute of Technology','Grand Forks','North Dakota',58207);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (13,'Alkharj University','Chicago','Illinois',60636);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (14,'State University of New York Health Sience Centre Syracuse','Las Vegas','Nevada',89125);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (15,'Royal Academy of Music','Scranton','Pennsylvania',18505);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (16,'Hobart and William Smith Colleges','Minneapolis','Minnesota',55417);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (17,'Australian Correspondence Schools','Fresno','California',93704);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (18,'Misamis University','Little Rock','Arkansas',72222);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (19,'Universidad Los Andes','Fort Pierce','Florida',34949);
INSERT INTO School(School_ID,School_Name,City,State,Zipcode) VALUES (20,'Chiang Mai University','Cleveland','Ohio',44118);
