use CourseHub;

INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (1,'Accounting',1);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (2,'Accounting',2);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (3,'Engineering',3);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (4,'Engineering',4);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (5,'Accounting',5);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (6,'Business Development',6);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (7,'Product Management',7);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (8,'Legal',8);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (9,'Services',9);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (10,'Marketing',10);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (11,'Accounting',11);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (12,'Legal',12);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (13,'Sales',13);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (14,'Business Development',14);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (15,'Training',15);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (16,'Product Management',16);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (17,'Sales',17);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (18,'Training',18);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (19,'Human Resources',19);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (20,'Services',20);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (21,'Training',1);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (22,'Engineering',2);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (23,'Business Development',3);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (24,'Engineering',4);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (25,'Training',5);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (26,'Support',6);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (27,'Sales',7);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (28,'Research and Development',8);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (29,'Engineering',9);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (30,'Product Management',10);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (31,'Business Development',11);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (32,'Engineering',12);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (33,'Research and Development',13);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (34,'Engineering',14);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (35,'Services',15);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (36,'Human Resources',16);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (37,'Accounting',17);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (38,'Marketing',18);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (39,'Services',19);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (40,'Marketing',20);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (41,'Support',1);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (42,'Product Management',2);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (43,'Engineering',3);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (44,'Marketing',4);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (45,'Marketing',5);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (46,'Human Resources',6);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (47,'Human Resources',7);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (48,'Marketing',8);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (49,'Services',9);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (50,'Product Management',10);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (51,'Accounting',11);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (52,'Marketing',12);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (53,'Services',13);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (54,'Legal',14);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (55,'Services',15);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (56,'Sales',16);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (57,'Research and Development',17);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (58,'Marketing',18);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (59,'Services',19);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (60,'Sales',20);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (61,'Support',1);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (62,'Product Management',2);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (63,'Marketing',3);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (64,'Engineering',4);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (65,'Accounting',5);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (66,'Engineering',6);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (67,'Business Development',7);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (68,'Services',8);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (69,'Research and Development',9);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (70,'Accounting',10);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (71,'Training',11);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (72,'Engineering',12);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (73,'Human Resources',13);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (74,'Human Resources',14);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (75,'Product Management',15);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (76,'Research and Development',16);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (77,'Sales',17);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (78,'Sales',18);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (79,'Engineering',19);
INSERT INTO Department(Department_ID,Department_Name,School_ID) VALUES (80,'Sales',20);
