use CourseHub;

INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (1,'Classroom Management',4,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (2,'SMSTS',4,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (3,'QPSK',4,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (4,'MDR',5,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (5,'EOQ',5,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (6,'Museums',4,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (7,'ODM',3,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (8,'Documentation',2,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (9,'LRO',5,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (10,'Computer Games',4,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (11,'CGI',1,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (12,'Luciferase Assay',4,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (13,'ICEM CFD',4,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (14,'XSI',5,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (15,'Outsourcing',3,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (16,'Xserve',1,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (17,'IVUS',1,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (18,'RVs',4,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (19,'JDE CNC',4,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (20,'SAP BPM',3,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (21,'Ajax4JSF',4,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (22,'Typo3',3,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (23,'Copy Typing',4,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (24,'Wedding DJ',5,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (25,'xCP',4,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (26,'MCDBA',2,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (27,'Situational Awareness',5,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (28,'Partnership Taxation',5,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (29,'Electrical Design',1,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (30,'Venture Capital',2,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (31,'LSAT',1,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (32,'Shopper Marketing',1,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (33,'DDE',5,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (34,'MVA',3,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (35,'LPN',1,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (36,'World War II',4,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (37,'CTRM',2,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (38,'MSP430',3,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (39,'HDSL',4,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (40,'LTSpice',1,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (41,'CMS-1500',3,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (42,'Digital TV',1,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (43,'Twist',4,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (44,'IOT',4,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (45,'Appraisals',3,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (46,'Welding',1,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (47,'Digital Electronics',3,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (48,'Kantar',4,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (49,'Earthquake Engineering',3,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (50,'WLST',4,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (51,'Drawing',1,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (52,'JDA E3',2,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (53,'Uniform Combined State Law',1,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (54,'Lithium-ion Batteries',4,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (55,'High Yield Bonds',5,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (56,'IRI Xlerate',3,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (57,'IRS Enrolled Agent',3,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (58,'Ghosts',5,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (59,'Graphic Design',1,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (60,'NVR',2,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (61,'Distributed Systems',5,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (62,'Private Events',4,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (63,'Power Plants',5,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (64,'WordPress',4,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (65,'System Architecture',5,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (66,'EBP',1,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (67,'Medical Devices',3,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (68,'Aerodynamics',2,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (69,'DUI Defense',1,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (70,'Robotics',5,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (71,'Kronos WFC',5,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (72,'HSSE',2,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (73,'NMT',5,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (74,'Slogans',4,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (75,'Linux System Administration',2,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (76,'Group Policy',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (77,'Xilinx ISE',4,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (78,'Eclipse CDT',3,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (79,'KBOX',5,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (80,'Steam Turbines',2,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (81,'Buyer&#39;s Agent',2,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (82,'Pre-sales',2,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (83,'Process Improvement',2,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (84,'Test Planning',4,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (85,'Rx',4,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (86,'BFSI',2,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (87,'Sound FX Editing',4,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (88,'Drafting Agreements',5,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (89,'OS X',5,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (90,'Environmental Awareness',5,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (91,'PQQ',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (92,'Evidence',5,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (93,'BTLS',3,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (94,'GFAAS',3,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (95,'WBS',2,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (96,'Teacher Training',5,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (97,'HD Video',1,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (98,'SLES',4,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (99,'OHSAS 18001',2,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (100,'TWiki',1,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (101,'Revenue Cycle',5,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (102,'IP VPN',3,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (103,'SGBD',1,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (104,'Beverage Industry',3,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (105,'Metro Ethernet',1,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (106,'jQTouch',5,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (107,'JTest',5,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (108,'RCP',5,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (109,'Hazard Recognition',1,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (110,'IMS DB/DC',1,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (111,'SVOD',4,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (112,'ERDAS Imagine',3,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (113,'PXI',5,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (114,'IOT',2,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (115,'MLD',3,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (116,'Swing',2,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (117,'Final Cut Pro',2,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (118,'Knowledge Management',1,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (119,'Vector NTI',1,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (120,'VSAT',4,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (121,'Urban Search &amp; Rescue',1,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (122,'Zinc',4,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (123,'Latin American Studies',1,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (124,'Pilates',4,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (125,'RV',1,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (126,'Attorneys',1,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (127,'Biostatistics',3,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (128,'Job Descriptions',2,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (129,'Frame Relay',4,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (130,'Juvederm',4,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (131,'RFC',4,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (132,'JIRA',3,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (133,'DUI Defense',5,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (134,'Oasys',3,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (135,'UDS',4,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (136,'FDA GMP',3,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (137,'DDL',4,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (138,'Upstream',5,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (139,'Motion Graphics',1,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (140,'Earned Value Management',2,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (141,'XAML',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (142,'eHRPD',3,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (143,'Office Management',1,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (144,'MBCS',2,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (145,'Constructive Feedback',3,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (146,'Rhino 3D',3,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (147,'UltraTax',2,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (148,'GL',4,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (149,'Utility Industry',1,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (150,'DGGE',2,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (151,'Oracle XE',3,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (152,'Windows 7',5,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (153,'OGC Gateway Reviews',5,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (154,'QML',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (155,'SLC500',4,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (156,'Overcome Objections',2,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (157,'Supply Chain Management',1,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (158,'YMS',5,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (159,'DFP',1,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (160,'Talent Acquisition',3,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (161,'Certified EKG Technician',2,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (162,'Alcoholic Beverages',5,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (163,'Corona SDK',5,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (164,'XLMiner',1,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (165,'VMware Certified Professional',2,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (166,'PC Games',5,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (167,'EPA',5,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (168,'XML-RPC',3,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (169,'RBAC',2,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (170,'YAML',1,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (171,'Account Reconciliation',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (172,'Military Aviation',2,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (173,'SFE',3,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (174,'HDS',3,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (175,'JProfiler',2,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (176,'Rheology',2,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (177,'Facilities Management',4,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (178,'KT',5,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (179,'CGI programming',1,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (180,'CFTC',5,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (181,'Veneers',2,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (182,'TPF',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (183,'Voice Acting',3,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (184,'Tax Advisory',3,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (185,'Career Development',1,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (186,'Xilinx ISE',5,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (187,'Apparel',4,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (188,'Machine Tools',4,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (189,'P&amp;ID',5,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (190,'Secretarial Skills',5,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (191,'TMJ Dysfunction',3,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (192,'IR Spectroscopy',3,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (193,'Knowledge Base',5,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (194,'Pneumatics',3,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (195,'Aquariums',5,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (196,'HDI',3,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (197,'eWFM',2,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (198,'EU Competition Law',3,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (199,'Bit.ly',2,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (200,'Program Evaluation',2,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (201,'Salesforce.com',3,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (202,'UI Automation',5,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (203,'Flight Planning',2,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (204,'Change Control',3,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (205,'Digital Strategy',5,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (206,'Sourcing',4,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (207,'Academic Tutoring',2,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (208,'WordPress',4,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (209,'Publications',5,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (210,'Utilities',1,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (211,'Analytical Skills',3,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (212,'EOI',2,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (213,'Eagle PCB',1,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (214,'Object Oriented Modeling',3,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (215,'Google Analytics',2,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (216,'BMD',2,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (217,'SQL Azure',3,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (218,'Typography',2,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (219,'Bathrooms',5,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (220,'Aircraft Maintenance',1,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (221,'Factory',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (222,'Corporate Finance',2,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (223,'Zmap',4,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (224,'WHIMS',1,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (225,'Supplier Evaluation',4,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (226,'Yardi Property Management',1,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (227,'MRTG',2,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (228,'Nitric Oxide',4,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (229,'Tourism Management',5,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (230,'LDI',5,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (231,'qPCR',2,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (232,'Ultimate Frisbee',2,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (233,'SGBD',4,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (234,'People-oriented',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (235,'Kitchen Remodeling',5,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (236,'European Studies',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (237,'Zinc',1,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (238,'European Union Politics',3,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (239,'ICT Consultancy',3,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (240,'Zend Studio',2,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (241,'Journal Entries',2,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (242,'Web Development',5,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (243,'Eurocodes',4,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (244,'Validation',1,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (245,'Zynx',1,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (246,'AQTESOLV',1,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (247,'NAS',1,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (248,'Undercover',1,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (249,'Active-HDL',4,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (250,'Jewelry',1,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (251,'IBM AIX',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (252,'GS1',1,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (253,'NGL',2,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (254,'CMBS',4,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (255,'DWH',1,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (256,'Two-phase Flow',1,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (257,'Cyber-security',5,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (258,'Three.js',3,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (259,'Guided Reading',3,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (260,'Ocean Freight',1,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (261,'eBusiness Suite',4,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (262,'RF Scanners',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (263,'Lustre',2,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (264,'JIT',4,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (265,'TDR',3,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (266,'Tortoise SVN',1,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (267,'Workers Compensation',1,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (268,'Medical Devices',3,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (269,'GIS Modeling',5,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (270,'CPM Scheduling',2,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (271,'OLA',4,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (272,'XML Schema',1,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (273,'BS25999',2,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (274,'Vehicle Dynamics',1,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (275,'RPG',4,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (276,'LVDS',5,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (277,'Alternative Energy',2,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (278,'Revenue Analysis',1,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (279,'Acute Care',1,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (280,'Account Reconciliation',1,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (281,'RCT',2,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (282,'SAP HR',1,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (283,'ISO 9000',4,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (284,'BPD',2,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (285,'Big 4',1,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (286,'Flex',3,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (287,'Rhino',5,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (288,'Abstraction',4,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (289,'EOC',1,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (290,'Fine Dining',1,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (291,'Microcontrollers',2,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (292,'Omnet++',1,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (293,'Organization Skills',2,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (294,'OMAP',5,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (295,'Test Driven Development',2,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (296,'Economic Development',5,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (297,'BJJ',5,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (298,'HSSE',3,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (299,'BMI',1,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (300,'JMF',4,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (301,'EoMPLS',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (302,'VMI',2,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (303,'HW/SW integration',3,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (304,'Variable Data Printing',1,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (305,'IVR',4,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (306,'Cisco Call Manager',5,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (307,'FNMA',4,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (308,'EE4',4,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (309,'Cardiac Rhythm Management',4,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (310,'ITIL',1,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (311,'Aspen HYSYS',2,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (312,'Program Evaluation',1,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (313,'Presentation Skills',2,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (314,'Business Process Improvement',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (315,'Myofascial Release',5,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (316,'Manual Therapy',1,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (317,'PDI',2,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (318,'SI',3,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (319,'FMEA',2,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (320,'Wyse',3,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (321,'WFO',5,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (322,'HDV',3,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (323,'NGOSS',5,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (324,'Office Equipment',2,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (325,'TWiki',2,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (326,'HSP',3,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (327,'Zooarchaeology',5,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (328,'MCEV',1,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (329,'Eclipse CDT',4,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (330,'Computer Science',2,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (331,'Zumba Instruction',5,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (332,'Social Media Outreach',2,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (333,'Accounts Payable',1,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (334,'XMLBeans',3,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (335,'Higher Education',3,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (336,'LVS',4,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (337,'Cognitive Psychology',2,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (338,'EHR',2,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (339,'RoboHelp',4,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (340,'Art History',3,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (341,'UVLayout',4,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (342,'Unfair Competition',3,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (343,'RF Design',2,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (344,'Metal Fabrication',2,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (345,'Hypertension',1,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (346,'HPHT',2,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (347,'JGrasp',5,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (348,'Market Analysis',3,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (349,'Bank Reconciliation',2,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (350,'RELAX NG',2,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (351,'PKCS',4,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (352,'Oracle XE',4,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (353,'OBIEE',4,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (354,'Analytical Ultracentrifugation',3,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (355,'Offset Printing',1,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (356,'SNF',5,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (357,'Control Systems Design',3,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (358,'Go-to-market Strategy',2,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (359,'Simple IRA',5,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (360,'Fashion Buying',3,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (361,'FTTH',4,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (362,'Income Tax',5,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (363,'Start-ups Management',5,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (364,'UDDI',2,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (365,'FTK',2,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (366,'Numerical Simulation',5,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (367,'Static Timing Analysis',4,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (368,'GxP',5,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (369,'UCP 600',5,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (370,'RTCP',4,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (371,'Siding',3,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (372,'Green Building',3,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (373,'Failure Analysis',4,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (374,'Amadeus',2,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (375,'Yacc',2,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (376,'Gastroenterology',2,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (377,'Architectural Design',3,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (378,'Biblical Studies',5,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (379,'Market Risk',5,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (380,'Athletic Training',4,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (381,'PMO set-up',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (382,'RELAX NG',3,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (383,'3D Visualization',1,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (384,'Environmental Science',5,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (385,'Patient Safety',2,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (386,'IntelliJ IDEA',3,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (387,'Knee Pain',4,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (388,'Database Administration',5,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (389,'Executive Protection',5,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (390,'HSS',2,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (391,'NDIS',5,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (392,'RRSP',1,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (393,'Fundraising',1,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (394,'Image Manipulation',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (395,'Koine Greek',1,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (396,'Broadband',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (397,'DME',5,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (398,'Objection Handling',4,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (399,'Union Avoidance',3,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (400,'VRTX',3,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (401,'SQL PL',4,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (402,'Criminal Investigations',3,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (403,'DFU',2,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (404,'BBQ',5,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (405,'AACR2',4,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (406,'Agents',4,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (407,'GNU Octave',2,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (408,'Swedish',1,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (409,'AAR',3,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (410,'BSR Advance',1,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (411,'Umbrella Insurance',3,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (412,'HSPA',4,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (413,'Glassfish',3,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (414,'Design of Experiments',2,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (415,'Xcart',1,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (416,'IEEE',4,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (417,'WMOS',5,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (418,'IaaS',5,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (419,'FDD',2,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (420,'Office Equipment',4,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (421,'Educational Leadership',5,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (422,'Oracle RAC',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (423,'SAP SD',4,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (424,'Medical Imaging',5,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (425,'Post Production',1,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (426,'EBA',2,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (427,'MYOB',5,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (428,'Groundwater',3,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (429,'Ext JS',4,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (430,'Homeland Security',5,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (431,'System Deployment',2,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (432,'Biology',2,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (433,'Lunch',1,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (434,'OTV',1,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (435,'JTA',2,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (436,'SIP',4,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (437,'Child Development',3,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (438,'Classroom',5,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (439,'Pharmaceutical Sales',4,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (440,'UAT Coordination',5,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (441,'WSGI',1,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (442,'Move Up Buyers',1,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (443,'Odyssey',3,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (444,'Wedding DJ',3,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (445,'Grief Counseling',4,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (446,'MyChart',5,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (447,'XACT',1,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (448,'Jeep',1,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (449,'Banquets',2,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (450,'VMware',1,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (451,'Fly Tying',2,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (452,'DMZ',3,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (453,'Nanomaterials',5,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (454,'Twitter Marketing',3,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (455,'Working at Height',3,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (456,'WFC',2,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (457,'KNX',4,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (458,'AC/DC',2,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (459,'BGAN',2,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (460,'SEM',2,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (461,'Commercial Photography',5,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (462,'Nursing Care',4,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (463,'IFW',4,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (464,'Cost Accounting',5,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (465,'RNP',4,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (466,'SGSN',4,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (467,'Xerox Printers',3,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (468,'Ergonomics',2,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (469,'Working at Height',2,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (470,'Hypertension',4,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (471,'Agarose Gel Electrophoresis',3,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (472,'Brokerage',5,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (473,'Radar',5,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (474,'Student Financial Aid',4,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (475,'Education',4,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (476,'Title Insurance',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (477,'FCNSA',3,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (478,'IRS',1,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (479,'European Markets',3,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (480,'Export',4,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (481,'Microsoft Dynamics SL',3,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (482,'OGC',5,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (483,'DWDM',3,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (484,'Xero',2,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (485,'Sports Management',5,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (486,'Requirements Gathering',3,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (487,'Fly Tying',5,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (488,'Property Management Systems',1,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (489,'Change Management',4,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (490,'MTA',3,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (491,'Window Displays',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (492,'Snow Leopard',3,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (493,'Gaming Industry',1,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (494,'FDTD',1,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (495,'Slide Shows',4,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (496,'Youth Programs',5,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (497,'Secretarial Skills',5,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (498,'Footwear',5,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (499,'Branch Banking',2,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (500,'DMX',2,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (501,'DDIC',3,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (502,'SRX',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (503,'Call Centers',3,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (504,'Transitional Justice',4,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (505,'PKCS',2,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (506,'Smartstream TLM',5,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (507,'Flame AA',2,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (508,'Sustainable Tourism',1,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (509,'TSS',2,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (510,'JSONP',1,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (511,'Pulse Oximetry',5,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (512,'User Interface Design',4,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (513,'Appeals',1,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (514,'Omnibus',5,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (515,'TIG Welding',1,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (516,'JDO',5,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (517,'FM200',1,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (518,'DWH',4,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (519,'GSD',5,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (520,'MCSA Security',1,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (521,'Hospitals',2,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (522,'QA Engineering',2,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (523,'RFI',5,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (524,'ESB',4,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (525,'ADP ezLaborManager',1,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (526,'GBA',2,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (527,'UK Corporation Tax',5,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (528,'WCCP',5,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (529,'CNC',3,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (530,'ODC',2,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (531,'TCPA',3,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (532,'Group Dynamics',4,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (533,'eGain',5,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (534,'EOR',4,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (535,'BCMS',3,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (536,'Glassfish',4,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (537,'Knowledge Discovery',5,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (538,'PDF Creator',4,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (539,'Linux Kernel',2,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (540,'MLP',4,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (541,'Jitter',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (542,'Medical Ultrasound',5,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (543,'SRT',2,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (544,'Clinical Development',5,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (545,'CQS',5,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (546,'UFS',3,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (547,'Citrix XenDesktop',3,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (548,'Fertility',1,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (549,'Epi Info',3,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (550,'Nightclub',2,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (551,'Eyelid Surgery',3,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (552,'VMware Fusion',5,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (553,'Handmade Jewelry',2,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (554,'Yamaha PM5D',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (555,'LLQP',3,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (556,'DLP',5,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (557,'NRP',4,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (558,'Affirmative Action',3,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (559,'Multimedia',3,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (560,'Language Teaching',5,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (561,'Laptops',5,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (562,'EOQ',4,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (563,'DMC',2,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (564,'CFDesign',3,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (565,'Zachman',3,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (566,'Certified EKG Technician',5,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (567,'Commercial Property Owners',2,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (568,'Rig',2,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (569,'Laptops',3,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (570,'Strategic HR',4,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (571,'HCP',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (572,'E-zines',1,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (573,'OAB',1,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (574,'Cashiering',4,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (575,'OEIC',1,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (576,'Active-HDL',4,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (577,'FM',4,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (578,'QuickBooks',4,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (579,'ASP.NET',3,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (580,'Marketing',4,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (581,'JUNOS',4,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (582,'JRun',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (583,'Strategic Thinking',5,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (584,'Safety Management Systems',5,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (585,'Trade Shows',4,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (586,'Igneous Petrology',3,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (587,'Facebook',1,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (588,'Character Rigging',2,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (589,'PyQt',4,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (590,'Knowledge Transfer',5,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (591,'Market Risk',3,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (592,'Copy Editing',2,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (593,'Quantitative Finance',1,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (594,'Business Analysis',1,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (595,'LDS',2,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (596,'NGS',4,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (597,'Surgery',4,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (598,'CD packaging',3,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (599,'Trading Systems',3,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (600,'Real Estate Development',1,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (601,'EWS',3,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (602,'IAM',5,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (603,'Ayurveda',3,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (604,'Thermodynamics',3,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (605,'PFT',5,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (606,'Smoking Cessation',4,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (607,'Pinterest',3,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (608,'LDD',1,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (609,'Unix',4,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (610,'GIS Application',1,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (611,'Publicity',3,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (612,'LMDS',1,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (613,'SAP EBP',3,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (614,'cXML',2,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (615,'Change Orders',5,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (616,'IIS',4,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (617,'PDMS Draft',5,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (618,'IASO',5,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (619,'FI-AA',4,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (620,'HCS 2000',3,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (621,'Digital TV',5,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (622,'Lytec',3,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (623,'Metal Fabrication',2,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (624,'SNF',3,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (625,'MRTG',2,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (626,'Sponsorship',1,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (627,'Thin Films',1,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (628,'Typesetting',3,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (629,'Oil &amp; Gas',1,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (630,'Disability Insurance',1,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (631,'CSPro',2,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (632,'Fundraising',2,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (633,'C-TPAT',5,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (634,'Snoring',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (635,'Snow Leopard',2,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (636,'Military',2,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (637,'Funding',3,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (638,'Hibernate',1,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (639,'KRAs',3,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (640,'CVS',2,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (641,'PV',1,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (642,'HUD',4,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (643,'Black &amp; White Photography',2,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (644,'WLST',5,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (645,'MQL',3,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (646,'Maritime Operations',4,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (647,'FSC certified',1,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (648,'Benefits Negotiation',5,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (649,'Apparel',4,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (650,'Islamic Finance',4,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (651,'OOS',5,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (652,'TMAP',2,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (653,'Skin Care Products',4,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (654,'Fund Of Funds',2,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (655,'TD-SCDMA',4,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (656,'Image Manipulation',4,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (657,'Zuora',4,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (658,'Public Policy',5,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (659,'Investment Banking',5,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (660,'Offshore Oil &amp; Gas',1,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (661,'SMED',1,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (662,'CMOS',5,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (663,'NSN',3,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (664,'Photojournalism',4,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (665,'Loan Origination',3,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (666,'MDA',4,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (667,'CCVP',2,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (668,'Thermodynamics',1,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (669,'osCommerce',5,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (670,'Auditing',2,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (671,'Classical Guitar',1,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (672,'Tourism',2,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (673,'Private Banking',5,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (674,'GWT',1,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (675,'Fashion Illustration',1,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (676,'Local Government',2,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (677,'Sybase IQ',3,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (678,'Go-to-market Strategy',2,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (679,'Leases',2,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (680,'Kyocera',4,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (681,'Rolling Stock',4,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (682,'Music Industry',3,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (683,'3Com NBX',5,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (684,'HD Camera Operation',5,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (685,'KDE',2,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (686,'High Sense Of Urgency',5,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (687,'Medicare',2,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (688,'BMP design',2,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (689,'Special Effects',1,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (690,'CX',1,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (691,'Zombies',1,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (692,'Vegetables',1,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (693,'Kidney Transplant',2,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (694,'Orthopedics',1,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (695,'Video Games',3,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (696,'TV News Production',1,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (697,'RLU',5,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (698,'Social Media Outreach',2,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (699,'Bhangra',4,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (700,'Professional Services',1,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (701,'Turkish',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (702,'Start-ups',2,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (703,'Political Science',2,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (704,'SAP BI',5,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (705,'Rheology',3,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (706,'Blogging',3,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (707,'Real Estate Transactions',1,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (708,'NPL',3,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (709,'Event Photography',1,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (710,'OmniGraffle',2,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (711,'PPMS',4,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (712,'iWay',3,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (713,'Niche Marketing',1,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (714,'BFSI',3,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (715,'PDM',3,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (716,'AMSI',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (717,'Healthy Eating',2,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (718,'Air Compressors',4,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (719,'Bloomberg Terminal',5,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (720,'BTS',3,80);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (721,'ILOG',1,1);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (722,'QinQ',1,2);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (723,'ODC',5,3);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (724,'NHL',3,4);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (725,'MXP',5,5);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (726,'DV',4,6);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (727,'GFSI',2,7);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (728,'Ektron Content Management System',1,8);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (729,'Genetics',2,9);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (730,'ZoomInfo',3,10);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (731,'CCP',4,11);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (732,'Gw Basic',2,12);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (733,'Organizational Effectiveness',2,13);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (734,'PTMS',3,14);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (735,'AVEVA PDMS',1,15);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (736,'Chemical Engineering',5,16);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (737,'Khalix',3,17);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (738,'Jewelry',4,18);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (739,'E-on Vue',5,19);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (740,'Weapons of Mass Destruction',1,20);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (741,'Fermentation',3,21);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (742,'Psychotherapy',1,22);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (743,'MVVM',4,23);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (744,'Qik',4,24);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (745,'Microsoft Technologies',5,25);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (746,'BPEL',3,26);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (747,'CQC',3,27);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (748,'Public Administration',1,28);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (749,'Electric Power',5,29);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (750,'Variance Analysis',2,30);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (751,'PVTsim',1,31);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (752,'TCAS',3,32);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (753,'Ayurveda',2,33);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (754,'MMORPG',2,34);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (755,'Commercial Litigation',5,35);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (756,'VC-1',1,36);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (757,'Warehouse Management',3,37);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (758,'World War II',3,38);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (759,'Job Fairs',1,39);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (760,'Start-ups',2,40);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (761,'Chemistry',2,41);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (762,'Sales Cycle Management',1,42);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (763,'CICS',3,43);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (764,'Smart TV',5,44);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (765,'Canon XH-A1',2,45);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (766,'Military Justice',4,46);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (767,'CDS',4,47);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (768,'JGroups',1,48);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (769,'SEO',5,49);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (770,'DSLAM',4,50);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (771,'Zend Studio',3,51);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (772,'GPFS',4,52);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (773,'Pro-IV',5,53);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (774,'AJAX',5,54);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (775,'CBORD',1,55);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (776,'Young People',2,56);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (777,'ILS',2,57);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (778,'TCLEOSE Instruction',1,58);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (779,'Duty Drawback',5,59);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (780,'Web Services',3,60);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (781,'Oil Industry',4,61);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (782,'HMIs',4,62);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (783,'Korean',2,63);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (784,'WFO',3,64);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (785,'ADP HRB',3,65);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (786,'User Interface Design',4,66);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (787,'LSS',2,67);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (788,'User Interface Design',5,68);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (789,'Xserve',1,69);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (790,'PCS7',3,70);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (791,'Nortel DMS',5,71);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (792,'NDT',2,72);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (793,'Fashion Jewelry',4,73);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (794,'Veneers',5,74);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (795,'Erosion Control',3,75);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (796,'Iron',4,76);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (797,'Wellness Coaching',5,77);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (798,'WDS',2,78);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (799,'Theatre',1,79);
INSERT INTO Course(Course_ID,Course_Name,Difficulty,Department_ID) VALUES (800,'BBEdit',2,80);
